services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  app:
    image: movie_app
    build: ./
    restart: always
    environment:
      - MONGO_DB_HOST=mongodb://mongo/movie
    ports:
      - 3200:3000